pub mod routes;
pub mod services;
pub mod types;

pub const HEADER: &str =
    "// Generated by hey-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.\n\n";

pub fn doc_comment(description: Option<&str>, indent: &str) -> String {
    match description {
        Some(text) => text
            .lines()
            .map(|line| format!("{indent}/// {}\n", line.trim_end()))
            .collect(),
        None => String::new(),
    }
}
