pub mod routes;
pub mod services;
pub mod types;

/// What every generated file starts with. Generated code is not lint-gated: the model
/// decides its names and shapes, and `clippy::all` alone would leave the rustc lints on.
pub const HEADER: &str = "// Generated by hey-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.\n\n#![allow(missing_docs, unreachable_pub, clippy::all, clippy::pedantic)]\n\n";

pub fn doc_comment(description: Option<&str>, indent: &str) -> String {
    match description {
        Some(text) => text
            .lines()
            .map(|line| format!("{indent}/// {}\n", line.trim_end()))
            .collect(),
        None => String::new(),
    }
}
