pub(crate) mod routes;
pub(crate) mod services;
pub(crate) mod types;

use std::fmt::Write;

/// What every generated file starts with. Generated code is not lint-gated: the model
/// decides its names and shapes, and `clippy::all` alone would leave the rustc lints on.
pub(crate) const HEADER: &str = "// Generated by hey-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.\n\n#![allow(missing_docs, unreachable_pub, clippy::all, clippy::pedantic)]\n\n";

pub(crate) fn doc_comment(description: Option<&str>, indent: &str) -> String {
    let mut out = String::new();
    for line in description.unwrap_or_default().lines() {
        writeln!(out, "{indent}/// {}", line.trim_end()).unwrap();
    }
    out
}
