import Foundation

let header = "// Generated by hey-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.\n\n"

/// Every generated file, keyed by its path under the generated directory.
func render(_ model: Model) -> [(String, String)] {
    var files: [(String, String)] = []
    files.append(("Routes.swift", renderRoutes(model)))
    files.append(("ServiceAccessors.swift", renderAccessors(model)))
    for schema in model.schemas {
        files.append(("Models/\(schema.name).swift", renderSchema(schema)))
    }
    for service in model.services {
        files.append(("Services/\(serviceClassName(service.name)).swift", renderService(service)))
    }
    return files
}

// MARK: - Models

func renderSchema(_ schema: Schema) -> String {
    var out = header
    out += docComment(schema.description, indent: "")
    switch schema.shape {
    case let .alias(kind):
        out += "public typealias \(schema.name) = \(swiftType(kind))\n"
    case let .structure(fields, polymorphic):
        out += renderStruct(schema.name, fields, polymorphic)
    }
    return out
}

/// Required members come first and take no default, so a body missing one fails to decode
/// rather than reading as a fabricated zero; optional members are optional and default to nil
/// in the initializer, so an absent member stays distinct from a present-but-empty one, and is
/// left off the wire on the way out. A member that names its own type is optional whatever the
/// model says, and one that is its own type is held through a box, since a struct cannot
/// contain itself.
private func renderStruct(_ name: String, _ fields: [Field], _ polymorphic: Polymorphic?) -> String {
    var out = "public struct \(name): Codable, Sendable, Equatable {\n"
    if fields.isEmpty {
        // A schema with no properties decodes from any object and encodes as an empty one.
        out += "    public init() {}\n}\n"
        return out
    }
    let ordered = fields.filter { $0.required && !$0.recursive } + fields.filter { !$0.required || $0.recursive }

    for field in ordered {
        let optional = !field.required || field.recursive
        let type = swiftType(field.kind) + (optional ? "?" : "")
        out += docComment(field.description, indent: "    ")
        if field.boxed {
            out += "    public var \(declared(field.wireName)): \(type) {\n"
            out += "        get { _\(identifier(field.wireName))?.value }\n"
            out += "        set { _\(identifier(field.wireName)) = newValue.map(Indirect.init) }\n"
            out += "    }\n"
        } else {
            out += "    public var \(declared(field.wireName)): \(type)\n"
        }
    }
    for field in ordered where field.boxed {
        out += "    private var _\(identifier(field.wireName)): Indirect<\(swiftType(field.kind))>?\n"
    }
    out += "\n"

    // The memberwise initializer, public, with nil defaults for what may be left out.
    let parameters = ordered.map { field -> String in
        let optional = !field.required || field.recursive
        let type = swiftType(field.kind) + (optional ? "?" : "")
        return "\(declared(field.wireName)): \(type)\(optional ? " = nil" : "")"
    }
    out += "    public init(\n"
    out += parameters.map { "        \($0)" }.joined(separator: ",\n")
    out += "\n    ) {\n"
    for field in ordered {
        let ident = identifier(field.wireName)
        let name = declared(field.wireName)
        if field.boxed {
            out += "        self._\(ident) = \(name).map(Indirect.init)\n"
        } else {
            out += "        self.\(name) = \(name)\n"
        }
    }
    out += "    }\n"

    if ordered.contains(where: { identifier($0.wireName) != $0.wireName || $0.boxed || declared($0.wireName) != identifier($0.wireName) }) {
        out += "\n    enum CodingKeys: String, CodingKey {\n"
        for field in ordered {
            let ident = identifier(field.wireName)
            let caseName = field.boxed ? "_\(ident)" : declared(field.wireName)
            if caseName == field.wireName {
                out += "        case \(caseName)\n"
            } else {
                out += "        case \(caseName) = \(literal(field.wireName))\n"
            }
        }
        out += "    }\n"
    }

    if let polymorphic {
        let discriminator = fields.first { $0.wireName == polymorphic.discriminator }
        let property = declared(polymorphic.discriminator)
        let optional = discriminator.map { !$0.required || $0.recursive } ?? true
        for variant in polymorphic.variants {
            let values = variant.values
            let aliases = values.count > 1 ? ", by any of the values HEY writes it as" : ""
            out += "\n    /// Whether the record's `\(polymorphic.discriminator)` is `\(variant.name)`\(aliases).\n"
            let test: String
            if values.count == 1 {
                test = "\(property) == \(literal(values[0]))"
            } else {
                let set = "[" + values.map(literal).joined(separator: ", ") + "]"
                test = optional ? "\(property).map { \(set).contains($0) } ?? false" : "\(set).contains(\(property))"
            }
            out += "    public var \(variantProperty(variant.name)): Bool { \(test) }\n"
        }
    }
    out += "}\n"
    return out
}

func swiftType(_ kind: FieldType) -> String {
    switch kind {
    case .string, .dateTime, .date: return "String"
    case .sensitiveString: return "SensitiveString"
    case .bool: return "Bool"
    case .int32: return "Int32"
    case .int64: return "Int"
    case .json: return "JSONValue"
    case let .named(name): return name
    case let .list(inner): return "[\(swiftType(inner))]"
    case let .map(inner): return "[String: \(swiftType(inner))]"
    }
}

// MARK: - Routes

func renderRoutes(_ model: Model) -> String {
    var out = header
    out += """
    /// Every route the model describes, one per operation, with the behaviour the Smithy model
    /// attaches to it: idempotency, the statuses that mean "nothing there", how it pages, and the
    /// retry policy.
    public enum Routes {

    """
    let operations = model.services.flatMap(\.operations).sorted { $0.id < $1.id }
    for operation in operations {
        out += "    /// `\(operation.httpMethod) \(operation.path)`\n"
        out += "    public static let \(routeConstant(operation.id)) = Route(\n"
        out += "        id: \(literal(operation.id)),\n"
        out += "        service: \(literal(pascalCase(operation.service))),\n"
        out += "        method: .\(operation.httpMethod.lowercased()),\n"
        out += "        path: \(literal(operation.path)),\n"
        out += "        pattern: \(literal(operation.path.hasSuffix(".json") ? String(operation.path.dropLast(5)) : operation.path)),\n"
        out += "        resource: \(literal(operation.resource)),\n"
        out += "        resourceType: \(literal(operation.resourceType)),\n"
        if operation.pathParams.isEmpty {
            out += "        params: [],\n"
        } else {
            out += "        params: [\n"
            for param in operation.pathParams {
                out += "            RouteParam(name: \(literal(param.wireName)), role: .\(param.role.rawValue), kind: .\(param.kind.rawValue)),\n"
            }
            out += "        ],\n"
        }
        out += "        idempotent: \(operation.idempotent),\n"
        out += "        readonly: \(operation.readonly),\n"
        out += "        html: \(operation.response.isHTML),\n"
        out += "        emptyOn: \(intList(operation.emptyOn)),\n"
        out += "        pagination: .\(operation.pagination == .none ? "unpaged" : operation.pagination.rawValue),\n"
        out += "        pageParameter: \(operation.pageParameter.map(literal) ?? "nil"),\n"
        out += "        retry: RetryPolicy(max: \(operation.retry.max), baseDelayMs: \(operation.retry.baseDelayMs), retryOn: \(intList(operation.retry.on)))\n"
        out += "    )\n\n"
    }
    out += "    /// Every route, in operation id order.\n"
    out += "    public static let all: [Route] = [\n"
    for operation in operations {
        out += "        \(routeConstant(operation.id)),\n"
    }
    out += "    ]\n}\n"
    return out
}

private func intList(_ values: [Int]) -> String { "[" + values.map(String.init).joined(separator: ", ") + "]" }

extension Response {
    var isHTML: Bool {
        if case .html = self { return true }
        return false
    }
}

// MARK: - Services

func renderService(_ service: Service) -> String {
    var out = header
    for operation in service.operations {
        out += renderOptions(operation)
    }
    out += "/// Service for \(pascalCase(service.name)) operations.\n"
    out += "public final class \(serviceClassName(service.name)): BaseService, @unchecked Sendable {\n"
    for (index, operation) in service.operations.enumerated() {
        if index > 0 { out += "\n" }
        out += renderMethod(operation)
    }
    out += "}\n"
    return out
}

private func renderOptions(_ operation: Operation) -> String {
    let optional = operation.queryParams.filter { !$0.required }
    guard !optional.isEmpty else { return "" }
    var out = "/// Options for \(operation.id).\n"
    out += "public struct \(operation.id)Options: Sendable, Equatable {\n"
    for param in optional {
        out += "    public var \(declared(param.wireName)): \(paramType(param.kind))?\n"
    }
    out += "\n    public init("
    out += optional.map { "\(declared($0.wireName)): \(paramType($0.kind))? = nil" }.joined(separator: ", ")
    out += ") {\n"
    for param in optional {
        out += "        self.\(declared(param.wireName)) = \(declared(param.wireName))\n"
    }
    out += "    }\n}\n\n"
    return out
}

private func renderMethod(_ operation: Operation) -> String {
    var arguments: [String] = []
    for param in operation.pathParams {
        arguments.append("\(identifier(param.wireName)): \(paramType(param.kind))")
    }
    for param in operation.queryParams where param.required {
        arguments.append("\(identifier(param.wireName)): \(paramType(param.kind))")
    }
    if let body = operation.body { arguments.append("body: \(body)") }
    let hasOptions = operation.queryParams.contains { !$0.required }
    if hasOptions { arguments.append("options: \(operation.id)Options? = nil") }

    var out = docComment(methodDoc(operation), indent: "    ")
    let returns = returnType(operation)
    out += "    public func \(operation.methodName)(\(arguments.joined(separator: ", "))) async throws\(returns.map { " -> \($0)" } ?? "") {\n"
    let pathArguments = operation.pathParams.map { identifier($0.wireName) }.joined(separator: ", ")
    let mutated = namedRecord(operation) != nil || !operation.queryParams.isEmpty || operation.body != nil
    out += "        \(mutated ? "var" : "let") operation = try client.operation(Routes.\(routeConstant(operation.id)), [\(pathArguments)])\n"
    if let param = namedRecord(operation) {
        let ident = identifier(param.wireName)
        out += "        operation.resourceId(\(param.kind == .int32 ? "Int(\(ident))" : ident))\n"
    }
    for param in operation.queryParams {
        let ident = identifier(param.wireName)
        if param.required {
            out += "        operation.query(\(literal(param.wireName)), \(ident))\n"
        } else {
            out += "        operation.queryOptional(\(literal(param.wireName)), options?.\(declared(param.wireName)))\n"
        }
    }
    if operation.body != nil {
        out += "        try operation.json(body)\n"
    }
    // Redirect statuses in emptyOn mean the redirect IS the answer (e.g. UpdateTopic's 302).
    if operation.emptyOn.contains(where: { $0 == 302 || $0 == 303 }) {
        out += "        operation.captureRedirects()\n"
    }
    out += "        return try await client.\(sendMethod(operation))(operation)\n"
    out += "    }\n"
    return out
}

private func methodDoc(_ operation: Operation) -> String {
    var lines: [String] = []
    if let description = operation.description?.trimmingCharacters(in: .whitespacesAndNewlines), !description.isEmpty {
        lines.append(description)
    }
    var parameters: [String] = []
    for param in operation.pathParams {
        parameters.append("\(identifier(param.wireName)): The \(humanReadable(param.wireName))")
    }
    for param in operation.queryParams where param.required {
        parameters.append("\(identifier(param.wireName)): The `\(param.wireName)` query parameter")
    }
    if operation.body != nil { parameters.append("body: Request body") }
    if operation.queryParams.contains(where: { !$0.required }) { parameters.append("options: Optional query parameters") }
    if !parameters.isEmpty {
        if !lines.isEmpty { lines.append("") }
        lines.append("- Parameters:")
        lines.append(contentsOf: parameters.map { "  - \($0)" })
    }
    return lines.joined(separator: "\n")
}

private func humanReadable(_ name: String) -> String {
    if name.hasSuffix("Id") {
        return snakeCase(String(name.dropLast(2))).replacingOccurrences(of: "_", with: " ") + " ID"
    }
    return snakeCase(name).replacingOccurrences(of: "_", with: " ")
}

/// The path parameter that names the record the operation acts on: the id in the last segment
/// when the path ends in one, and otherwise the outermost parent's. A name or a date says
/// nothing an observer can look a record up by, so only numbers count.
private func namedRecord(_ operation: Operation) -> PathParam? {
    let numbered = operation.pathParams.filter { $0.kind == .int32 || $0.kind == .int64 }
    return numbered.first { $0.role == .recording } ?? numbered.first { $0.role == .parent }
}

private func returnType(_ operation: Operation) -> String? {
    switch operation.response {
    case .empty: return nil
    case .html: return "String"
    case let .json(name):
        if operation.pagination != .none { return "Page<\(name)>" }
        if !operation.emptyOn.isEmpty { return "\(name)?" }
        return name
    }
}

private func sendMethod(_ operation: Operation) -> String {
    switch operation.response {
    case .empty: return "sendVoid"
    case .html: return "sendText"
    case .json:
        if operation.pagination != .none { return "sendPage" }
        if !operation.emptyOn.isEmpty { return "sendOptional" }
        return "send"
    }
}

func paramType(_ kind: ParamKind) -> String {
    switch kind {
    case .string: return "String"
    case .bool: return "Bool"
    case .int32: return "Int32"
    case .int64: return "Int"
    }
}

// MARK: - Client accessors

func renderAccessors(_ model: Model) -> String {
    var out = header
    out += "extension HeyClient {\n"
    for (index, service) in model.services.enumerated() {
        if index > 0 { out += "\n" }
        out += "    /// \(pascalCase(service.name)) operations.\n"
        out += "    public var \(serviceAccessorName(service.name)): \(serviceClassName(service.name)) { \(serviceClassName(service.name))(client: self) }\n"
    }
    out += "}\n"
    return out
}

// MARK: - Helpers

/// A documentation comment for a description, or nothing for none.
func docComment(_ description: String?, indent: String) -> String {
    guard let text = description?.trimmingCharacters(in: .whitespacesAndNewlines), !text.isEmpty else { return "" }
    return text.split(separator: "\n", omittingEmptySubsequences: false).map { line in
        let trimmed = line.reversed().drop { $0 == " " || $0 == "\t" }.reversed()
        return trimmed.isEmpty ? "\(indent)///\n" : "\(indent)/// \(String(trimmed))\n"
    }.joined()
}

/// A Swift string literal for a value, with the characters that would break one escaped.
func literal(_ value: String) -> String {
    var out = "\""
    for character in value.unicodeScalars {
        switch character {
        case "\\": out += "\\\\"
        case "\"": out += "\\\""
        case "\n": out += "\\n"
        case "\r": out += "\\r"
        case "\t": out += "\\t"
        default: out.unicodeScalars.append(character)
        }
    }
    return out + "\""
}
