package com.basecamp.hey.generator

const val HEADER = "// Generated by hey-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.\n\n"

/** Every generated file, keyed by its path under the generated directory. */
fun render(model: Model): Map<String, String> {
    val files = linkedMapOf<String, String>()
    files["Routes.kt"] = renderRoutes(model)
    files["ServiceAccessors.kt"] = renderAccessors(model)
    for (schema in model.schemas) {
        files["models/${schema.name}.kt"] = renderSchema(schema)
    }
    for (service in model.services) {
        files["services/${serviceClassName(service.name)}.kt"] = renderService(service, model)
    }
    return files
}

// ---------------------------------------------------------------------------------------
// Models

fun renderSchema(schema: Schema): String = buildString {
    append(HEADER)
    appendLine("package com.basecamp.hey.generated.models")
    appendLine()
    val imports = sortedSetOf<String>()
    when (val shape = schema.shape) {
        is Shape.Alias -> collectImports(shape.kind, imports)
        is Shape.Struct -> {
            imports += "kotlinx.serialization.Serializable"
            for (field in shape.fields) {
                collectImports(field.kind, imports)
                if (fieldIdent(field.wireName).trim('`') != field.wireName) imports += "kotlinx.serialization.SerialName"
            }
        }
    }
    for (import in imports) appendLine("import $import")
    if (imports.isNotEmpty()) appendLine()
    append(kdoc(schema.description, ""))
    when (val shape = schema.shape) {
        is Shape.Alias -> appendLine("typealias ${schema.name} = ${kotlinType(shape.kind)}")
        is Shape.Struct -> renderStruct(this, schema.name, shape)
    }
}

private fun collectImports(kind: FieldType, imports: MutableSet<String>) {
    when (kind) {
        FieldType.SensitiveStr -> imports += "com.basecamp.hey.SensitiveString"
        FieldType.Json -> imports += "kotlinx.serialization.json.JsonElement"
        is FieldType.ListOf -> collectImports(kind.inner, imports)
        is FieldType.MapOf -> collectImports(kind.inner, imports)
        else -> {}
    }
}

/**
 * Required members come first without defaults, so a body missing one fails to decode
 * rather than reading as a fabricated zero; optional members are nullable and default to
 * null, so an absent member stays distinct from a present-but-empty one. A member that
 * names its own type is nullable whatever the model says, since it can have no default.
 */
private fun renderStruct(out: StringBuilder, name: String, shape: Shape.Struct) {
    out.appendLine("@Serializable")
    if (shape.fields.isEmpty()) {
        // A data class needs a member; a schema with no properties is a plain class that
        // decodes from any object and encodes as an empty one.
        out.appendLine("class $name")
        return
    }
    out.appendLine("data class $name(")
    val ordered = shape.fields.filter { it.required && !it.recursive } + shape.fields.filter { !it.required || it.recursive }
    for (field in ordered) {
        out.append(kdoc(field.description, "    "))
        val ident = fieldIdent(field.wireName)
        if (ident.trim('`') != field.wireName) {
            out.append("    @SerialName(${literal(field.wireName)})\n")
        }
        val nullable = !field.required || field.recursive
        val type = kotlinType(field.kind) + if (nullable) "?" else ""
        val default = if (nullable) " = null" else ""
        out.appendLine("    val $ident: $type$default,")
    }
    out.append(")")
    val polymorphic = shape.polymorphic
    if (polymorphic != null) {
        val discriminator = fieldIdent(polymorphic.discriminator)
        out.appendLine(" {")
        for (variant in polymorphic.variants) {
            val values = variant.values
            val test = if (values.size == 1) "$discriminator == ${literal(values.single())}" else "$discriminator in setOf(${values.joinToString(", ") { literal(it) }})"
            out.appendLine("    /** Whether the record's `${polymorphic.discriminator}` is `${variant.name}`${if (values.size > 1) ", by any of the values HEY writes it as" else ""}. */")
            out.appendLine("    val ${variantProperty(variant.name)}: Boolean get() = $test")
            out.appendLine()
        }
        out.setLength(out.length - 1)
        out.appendLine("}")
    } else {
        out.appendLine()
    }
}

fun kotlinType(kind: FieldType): String = when (kind) {
    FieldType.Str, FieldType.DateTime, FieldType.Date -> "String"
    FieldType.SensitiveStr -> "SensitiveString"
    FieldType.Bool -> "Boolean"
    FieldType.Int32 -> "Int"
    FieldType.Int64 -> "Long"
    FieldType.Json -> "JsonElement"
    is FieldType.Named -> kind.name
    is FieldType.ListOf -> "List<${kotlinType(kind.inner)}>"
    is FieldType.MapOf -> "Map<String, ${kotlinType(kind.inner)}>"
}

// ---------------------------------------------------------------------------------------
// Routes

fun renderRoutes(model: Model): String = buildString {
    append(HEADER)
    appendLine("package com.basecamp.hey.generated")
    appendLine()
    appendLine("import com.basecamp.hey.Method")
    appendLine("import com.basecamp.hey.Pagination")
    appendLine("import com.basecamp.hey.ParamKind")
    appendLine("import com.basecamp.hey.ParamRole")
    appendLine("import com.basecamp.hey.RetryPolicy")
    appendLine("import com.basecamp.hey.Route")
    appendLine("import com.basecamp.hey.RouteParam")
    appendLine()
    appendLine("/**")
    appendLine(" * Every route the model describes, one per operation, with the behaviour the Smithy model")
    appendLine(" * attaches to it: idempotency, the statuses that mean \"nothing there\", how it pages, and")
    appendLine(" * the retry policy.")
    appendLine(" */")
    appendLine("object Routes {")
    val operations = model.services.flatMap { it.operations }.sortedBy { it.id }
    for (operation in operations) {
        appendLine("    /** `${operation.httpMethod} ${operation.path}` */")
        appendLine("    val ${constantName(operation.id)}: Route = Route(")
        appendLine("        id = ${literal(operation.id)},")
        appendLine("        service = ${literal(operation.service.toPascalCase())},")
        appendLine("        method = Method.${operation.httpMethod},")
        appendLine("        path = ${literal(operation.path)},")
        appendLine("        pattern = ${literal(operation.path.removeSuffix(".json"))},")
        appendLine("        resource = ${literal(operation.resource)},")
        appendLine("        resourceType = ${literal(operation.resourceType)},")
        if (operation.pathParams.isEmpty()) {
            appendLine("        params = emptyList(),")
        } else {
            appendLine("        params = listOf(")
            for (param in operation.pathParams) {
                appendLine("            RouteParam(${literal(param.wireName)}, ParamRole.${param.role.name}, ParamKind.${param.kind.name}),")
            }
            appendLine("        ),")
        }
        appendLine("        idempotent = ${operation.idempotent},")
        appendLine("        readonly = ${operation.readonly},")
        appendLine("        html = ${operation.response is Response.Html},")
        appendLine("        emptyOn = ${intList(operation.emptyOn)},")
        appendLine("        pagination = Pagination.${operation.pagination.name},")
        appendLine("        pageParameter = ${operation.pageParameter?.let(::literal) ?: "null"},")
        appendLine("        retry = RetryPolicy(max = ${operation.retry.max}, baseDelayMs = ${operation.retry.baseDelayMs}L, retryOn = ${intList(operation.retry.on)}),")
        appendLine("    )")
        appendLine()
    }
    appendLine("    /** Every route, in operation id order. */")
    appendLine("    val ALL: List<Route> = listOf(")
    for (operation in operations) {
        appendLine("        ${constantName(operation.id)},")
    }
    appendLine("    )")
    appendLine("}")
}

private fun intList(values: List<Int>): String =
    if (values.isEmpty()) "emptyList()" else "listOf(${values.joinToString(", ")})"

// ---------------------------------------------------------------------------------------
// Services

fun renderService(service: Service, model: Model): String = buildString {
    val className = serviceClassName(service.name)
    append(HEADER)
    appendLine("package com.basecamp.hey.generated.services")
    appendLine()
    val imports = sortedSetOf("com.basecamp.hey.HeyClient", "com.basecamp.hey.generated.Routes", "com.basecamp.hey.services.BaseService")
    if (service.operations.any { it.pagination != Pagination.NONE && it.response is Response.Json }) {
        imports += "com.basecamp.hey.Page"
    }
    if (service.operations.any { it.body != null }) imports += "com.basecamp.hey.json"
    for (operation in service.operations) {
        operation.body?.let { imports += "com.basecamp.hey.generated.models.$it" }
        (operation.response as? Response.Json)?.let { imports += "com.basecamp.hey.generated.models.${it.name}" }
    }
    for (import in imports) appendLine("import $import")
    appendLine()

    for (operation in service.operations) {
        renderOptions(this, operation)
    }

    appendLine("/**")
    appendLine(" * Service for ${service.name.toPascalCase()} operations.")
    appendLine(" *")
    appendLine(" * @generated from OpenAPI spec — do not edit directly")
    appendLine(" */")
    // A service with a hand-written subclass is open so the subclass can add to it.
    val keyword = if (model.naming.handWrittenServiceFor(service.name) != null) "open class" else "class"
    appendLine("$keyword $className(client: HeyClient) : BaseService(client) {")
    for ((index, operation) in service.operations.withIndex()) {
        if (index > 0) appendLine()
        renderMethod(this, operation)
    }
    appendLine("}")
}

private fun renderOptions(out: StringBuilder, operation: Operation) {
    val optional = operation.queryParams.filter { !it.required }
    if (optional.isEmpty()) return
    out.appendLine("/** Options for ${operation.id}. */")
    out.appendLine("data class ${operation.id}Options(")
    for (param in optional) {
        out.appendLine("    val ${fieldIdent(param.wireName)}: ${paramType(param.kind)}? = null,")
    }
    out.appendLine(")")
    out.appendLine()
}

private fun renderMethod(out: StringBuilder, operation: Operation) {
    val arguments = mutableListOf<String>()
    for (param in operation.pathParams) {
        arguments += "${fieldIdent(param.wireName)}: ${paramType(param.kind)}"
    }
    for (param in operation.queryParams.filter { it.required }) {
        arguments += "${fieldIdent(param.wireName)}: ${paramType(param.kind)}"
    }
    operation.body?.let { arguments += "body: $it" }
    val hasOptions = operation.queryParams.any { !it.required }
    if (hasOptions) {
        arguments += "options: ${operation.id}Options? = null"
    }

    out.append(kdoc(methodDoc(operation), "    "))
    out.appendLine("    suspend fun ${operation.methodName}(${arguments.joinToString(", ")}): ${returnType(operation)} {")
    val pathArguments = operation.pathParams.joinToString(", ") { fieldIdent(it.wireName) }
    out.appendLine("        val operation = client.operation(Routes.${constantName(operation.id)}, listOf($pathArguments))")
    namedRecord(operation)?.let { param ->
        out.appendLine("        operation.resourceId(${resourceId(param)})")
    }
    for (param in operation.queryParams) {
        val ident = fieldIdent(param.wireName)
        if (param.required) {
            out.appendLine("        operation.query(${literal(param.wireName)}, $ident)")
        } else {
            out.appendLine("        operation.queryOptional(${literal(param.wireName)}, options?.$ident)")
        }
    }
    if (operation.body != null) {
        out.appendLine("        operation.json(body)")
    }
    // Redirect statuses in emptyOn mean the redirect IS the answer (e.g. UpdateTopic's 302).
    if (operation.emptyOn.any { it == 302 || it == 303 }) {
        out.appendLine("        operation.captureRedirects()")
    }
    out.appendLine("        return client.${sendMethod(operation)}(operation)")
    out.appendLine("    }")
}

private fun methodDoc(operation: Operation): String = buildString {
    operation.description?.trim()?.takeIf { it.isNotEmpty() }?.let { append(it) }
    for (param in operation.pathParams) {
        if (isNotEmpty()) append("\n")
        append("@param ${fieldIdent(param.wireName).trim('`')} The ${param.wireName.toHumanReadable()}")
    }
    for (param in operation.queryParams.filter { it.required }) {
        if (isNotEmpty()) append("\n")
        append("@param ${fieldIdent(param.wireName).trim('`')} The `${param.wireName}` query parameter")
    }
    if (operation.body != null) {
        if (isNotEmpty()) append("\n")
        append("@param body Request body")
    }
    if (operation.queryParams.any { !it.required }) {
        if (isNotEmpty()) append("\n")
        append("@param options Optional query parameters")
    }
}

private fun String.toHumanReadable(): String =
    if (endsWith("Id")) removeSuffix("Id").toSnakeCase().replace('_', ' ') + " ID" else toSnakeCase().replace('_', ' ')

/**
 * The path parameter that names the record the operation acts on: the id in the last
 * segment when the path ends in one, and otherwise the outermost parent's. A name or a
 * date says nothing an observer can look a record up by, so only numbers count.
 */
private fun namedRecord(operation: Operation): PathParam? =
    numbered(operation, ParamRole.RECORDING).firstOrNull() ?: numbered(operation, ParamRole.PARENT).firstOrNull()

private fun numbered(operation: Operation, role: ParamRole): List<PathParam> =
    operation.pathParams.filter { it.role == role && (it.kind == ParamKind.INT32 || it.kind == ParamKind.INT64) }

private fun resourceId(param: PathParam): String {
    val ident = fieldIdent(param.wireName)
    return if (param.kind == ParamKind.INT32) "$ident.toLong()" else ident
}

private fun paginated(operation: Operation): Boolean = operation.pagination != Pagination.NONE

private fun returnType(operation: Operation): String {
    val response = operation.response
    return when {
        response is Response.Empty -> "Unit"
        response is Response.Html -> "String"
        response is Response.Json && paginated(operation) -> "Page<${response.name}>"
        response is Response.Json && operation.emptyOn.isNotEmpty() -> "${response.name}?"
        response is Response.Json -> response.name
        else -> throw GeneratorException("${operation.id}: unsupported response")
    }
}

private fun sendMethod(operation: Operation): String {
    val response = operation.response
    return when {
        response is Response.Empty -> "sendUnit"
        response is Response.Html -> "sendText"
        paginated(operation) -> "sendPage"
        operation.emptyOn.isNotEmpty() -> "sendOptional"
        else -> "send"
    }
}

fun paramType(kind: ParamKind): String = when (kind) {
    ParamKind.STRING -> "String"
    ParamKind.BOOL -> "Boolean"
    ParamKind.INT32 -> "Int"
    ParamKind.INT64 -> "Long"
}

// ---------------------------------------------------------------------------------------
// Client accessors

fun renderAccessors(model: Model): String = buildString {
    append(HEADER)
    appendLine("package com.basecamp.hey.generated")
    appendLine()
    appendLine("import com.basecamp.hey.HeyClient")
    appendLine("import com.basecamp.hey.generated.services.*")
    appendLine()
    appendLine("/**")
    appendLine(" * Generated service accessor extensions for [HeyClient].")
    appendLine(" *")
    appendLine(" * These properties provide lazy, cached access to all HEY API services.")
    appendLine(" *")
    appendLine(" * @generated from OpenAPI spec — do not edit directly")
    appendLine(" */")
    appendLine()
    for (service in model.services) {
        // Hand-written subclasses are constructed and declared by their fully-qualified name
        // so their convenience methods are visible on the accessor without caller imports.
        val className = model.naming.handWrittenServiceFor(service.name) ?: serviceClassName(service.name)
        appendLine("/** ${service.name.toPascalCase()} operations. */")
        appendLine("val HeyClient.${serviceAccessorName(service.name)}: $className")
        appendLine("    get() = service(${literal(service.name.toPascalCase())}) { $className(this) }")
        appendLine()
    }
    setLength(length - 1)
}

// ---------------------------------------------------------------------------------------
// Helpers

/** A KDoc block for a description, or nothing for none. */
fun kdoc(description: String?, indent: String): String {
    val text = description?.trim()?.takeIf { it.isNotEmpty() } ?: return ""
    val lines = text.replace("*/", "* /").lines()
    return buildString {
        appendLine("$indent/**")
        for (line in lines) {
            appendLine(if (line.isBlank()) "$indent *" else "$indent * ${line.trimEnd()}")
        }
        appendLine("$indent */")
    }
}

/** A Kotlin string literal for a value, with the characters that would break one escaped. */
fun literal(value: String): String = buildString {
    append('"')
    for (character in value) {
        when (character) {
            '\\' -> append("\\\\")
            '"' -> append("\\\"")
            '$' -> append("\\$")
            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            else -> append(character)
        }
    }
    append('"')
}
